import type { GameItem } from '@dgbook/edugame-core';
import { useEffect, useMemo, useRef } from 'react';
import { stableChallengeOrder } from './challenge-order';

type Target = { id: string; label: string };

export function BeamTuningArcade({ items, targets, selected, doneIds, combo, result, active, levelStep, onSelect, onDrop }: {
  items: GameItem[]; targets: Target[]; selected: GameItem | null; doneIds: string[]; combo: number;
  result: 'idle' | 'correct' | 'wrong' | 'complete'; active: boolean; levelStep: number;
  onSelect: (item: GameItem) => void; onDrop: (targetId: string) => void;
}) {
  const ordered = useMemo(() => stableChallengeOrder(items, `beam-tuning-${levelStep}`), [items, levelStep]);
  const positions = [['11%', '18%'], ['48%', '12%'], ['20%', '57%'], ['55%', '55%'], ['36%', '35%']] as const;
  return <section className={`eg-beam-tuning${result === 'wrong' ? ' is-shake' : ''}`} data-beam-tuning-arcade data-stage={levelStep + 1}>
    <header><ol>{['扇区校准', '姿态联调', '覆盖验证'].map((label, index) => <li className={index <= levelStep ? 'is-active' : ''} key={label}><b>{index + 1}</b>{label}</li>)}</ol><span>{combo > 1 ? `稳定调优 x${combo}` : '参数必须对应空间证据'}</span></header>
    <div className="eg-beam-stage"><BeamTuningCanvas /><div className="eg-beam-map"><span className="eg-beam-site">gNB-A3<small>东南扇区</small></span><span className="eg-beam-building">遮挡楼体</span><i className="eg-beam-road" /><div className="eg-beam-targets">{targets.map((target, index) => <button className={selected?.target_id === target.id ? 'is-match' : ''} data-edugame-correct={selected ? selected.correct !== false && selected.target_id === target.id : false} data-edugame-target={target.id} disabled={!active || !selected} key={target.id} onClick={() => onDrop(target.id)} style={{ left: positions[index % positions.length]?.[0], top: positions[index % positions.length]?.[1] }} type="button"><i />{target.label}</button>)}</div></div><aside><strong>参数与测量证据</strong><small>先选择记录，再接入波束模型</small>{ordered.map((item) => { const done = doneIds.includes(item.id); return <button className={`${selected?.id === item.id ? 'is-selected' : ''}${done ? ' is-done' : ''}`} data-edugame-correct={item.correct !== false ? 'true' : 'false'} data-edugame-item={item.id} data-edugame-target-id={item.target_id ?? ''} disabled={!active || done} key={item.id} onClick={() => onSelect(item)} type="button"><span>{item.correct === false ? '风险' : '参数'}</span><strong>{item.label}</strong></button>; })}</aside></div>
    <style>{styles}</style>
  </section>;
}

function BeamTuningCanvas() {
  const hostRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => { let app: any; let destroyed = false; import('pixi.js').then(async (PIXI) => { if (!hostRef.current || destroyed) return; app = new PIXI.Application(); await app.init({ width: 960, height: 540, background: '#061521', antialias: true, resolution: Math.min(window.devicePixelRatio || 1, 1.5) }); if (!hostRef.current || destroyed) { app.destroy(true); return; } hostRef.current.innerHTML = ''; hostRef.current.appendChild(app.canvas); const map = new PIXI.Graphics(); map.rect(0, 0, 960, 540).fill(0x061521); for (let x = 0; x < 960; x += 48) map.moveTo(x, 0).lineTo(x, 540).stroke({ width: 1, color: 0x173a4c, alpha: .48 }); for (let y = 0; y < 540; y += 48) map.moveTo(0, y).lineTo(960, y).stroke({ width: 1, color: 0x173a4c, alpha: .48 }); map.circle(185, 365, 18).fill(0x22d3ee); map.poly([185, 365, 720, 92, 745, 300]).fill({ color: 0x7c5cff, alpha: .16 }).stroke({ width: 2, color: 0x8b7cff, alpha: .78 }); map.rect(530, 115, 140, 170).fill({ color: 0x233c4c, alpha: .96 }).stroke({ width: 2, color: 0xf59e0b, alpha: .78 }); app.stage.addChild(map); const pulse = new PIXI.Graphics(); app.stage.addChild(pulse); let tick = 0; const animate = (ticker: any) => { tick += (ticker?.deltaTime ?? 1) * .04; pulse.clear(); for (let r = 0; r < 3; r += 1) pulse.circle(185, 365, 34 + ((tick * 20 + r * 38) % 110)).stroke({ width: 2, color: 0x22d3ee, alpha: .6 - r * .14 }); }; animate({ deltaTime: 0 }); if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) app.ticker.add(animate); }).catch(() => { if (hostRef.current) hostRef.current.dataset.fallback = 'true'; }); return () => { destroyed = true; app?.destroy(true, { children: true }); }; }, []);
  return <div aria-hidden="true" className="eg-pixi-canvas eg-beam-canvas" ref={hostRef} />;
}

const styles = `
.eg-beam-tuning{display:grid;gap:8px;color:#e5f6ff}.eg-beam-tuning>header{display:flex;align-items:center;justify-content:space-between}.eg-beam-tuning ol{display:flex;gap:10px;margin:0;padding:0;list-style:none}.eg-beam-tuning li{display:flex;align-items:center;gap:6px;color:#6f8da1;font-size:10px}.eg-beam-tuning li b{width:22px;height:22px;display:grid;place-items:center;border:1px solid #36576c;border-radius:50%}.eg-beam-tuning li.is-active{color:#e0fbff}.eg-beam-tuning li.is-active b{border-color:#32d5cf;color:#052431;background:#49e5dc}.eg-beam-tuning>header span{color:#f5ca62;font-size:10px}.eg-beam-stage{position:relative;height:400px;overflow:hidden;border:1px solid #244b61;border-radius:7px;background:#061521}.eg-beam-canvas,.eg-beam-canvas canvas{position:absolute!important;inset:0;width:100%!important;height:100%!important;object-fit:cover}.eg-beam-map{position:absolute;z-index:2;inset:0 250px 0 0}.eg-beam-map>span{position:absolute;border:1px solid #3d667d;border-radius:4px;padding:7px 9px;color:#e1f4ff;background:#082337e8;font-size:10px;font-weight:850}.eg-beam-map>span small{display:block;color:#75a1b5;font-size:8px}.eg-beam-site{left:14%;bottom:17%}.eg-beam-building{right:17%;top:22%;border-color:#b87827!important;color:#ffe4a4!important}.eg-beam-road{position:absolute;right:-5%;bottom:20%;left:-5%;height:18px;border-top:2px dashed #57788d;border-bottom:2px dashed #57788d;transform:rotate(-11deg)}.eg-beam-targets button{position:absolute;max-width:135px;border:1px solid #365d72;border-radius:4px;padding:6px 8px;color:#c7e1ed;background:#08243bdc;font-size:9px;text-align:left}.eg-beam-targets button i{display:inline-block;width:7px;height:7px;margin-right:5px;border-radius:50%;background:#43d8d2}.eg-beam-targets button.is-match{border-color:#fde047;box-shadow:0 0 17px #fde04733}.eg-beam-stage>aside{position:absolute;z-index:4;top:0;right:0;bottom:0;width:250px;display:grid;align-content:start;gap:6px;border-left:1px solid #27495d;padding:13px;background:#071927ed}.eg-beam-stage>aside>strong{font-size:12px}.eg-beam-stage>aside>small{margin-bottom:4px;color:#7595a7;font-size:8px}.eg-beam-stage>aside button{display:grid;grid-template-columns:38px 1fr;align-items:center;gap:7px;min-height:48px;border:1px solid #294a5e;border-radius:4px;padding:6px;color:#dceff8;background:#092235;text-align:left}.eg-beam-stage>aside button span{color:#42d5ce;font-size:8px}.eg-beam-stage>aside button strong{font-size:9px}.eg-beam-stage>aside button.is-selected{border-color:#fde047}.eg-beam-stage>aside button.is-done{opacity:.34}.eg-beam-tuning.is-shake{animation:egBeamShake .24s linear}@keyframes egBeamShake{25%{transform:translateX(-4px)}75%{transform:translateX(4px)}}
`;
