import type { GameItem } from '@dgbook/edugame-core';
import { useEffect, useMemo, useRef } from 'react';
import { stableChallengeOrder } from './challenge-order';

type Target = { id: string; label: string };

export function EvidenceChainArcade({ items, targets, selected, doneIds, combo, result, active, levelStep, onSelect, onDrop }: {
  items: GameItem[]; targets: Target[]; selected: GameItem | null; doneIds: string[]; combo: number;
  result: 'idle' | 'correct' | 'wrong' | 'complete'; active: boolean; levelStep: number;
  onSelect: (item: GameItem) => void; onDrop: (targetId: string) => void;
}) {
  const ordered = useMemo(() => stableChallengeOrder(items, `evidence-chain-${levelStep}`), [items, levelStep]);
  return <section className={`eg-evidence-chain${result === 'wrong' ? ' is-shake' : ''}`} data-evidence-chain-arcade data-stage={levelStep + 1}>
    <header><div><span>现场档案室</span><strong>{['归档对象', '建立索引', '形成结论'][levelStep] ?? '证据复核'}</strong></div><em>{combo > 1 ? `连续归档 x${combo}` : `${doneIds.length}/${ordered.filter((item) => item.correct !== false).length} 已归档`}</em></header>
    <div className="eg-evidence-stage"><EvidenceChainCanvas /><div className="eg-evidence-inbox"><small>待核材料</small>{ordered.map((item) => { const done = doneIds.includes(item.id); return <button className={`${selected?.id === item.id ? 'is-selected' : ''}${done ? ' is-done' : ''}`} data-edugame-correct={item.correct !== false ? 'true' : 'false'} data-edugame-item={item.id} data-edugame-target-id={item.target_id ?? ''} disabled={!active || done} key={item.id} onClick={() => onSelect(item)} type="button"><i>{item.correct === false ? '!' : 'E'}</i><span><strong>{item.label}</strong><small>{item.correct === false ? '待判断风险项' : '现场证据'}</small></span></button>; })}</div><div className="eg-evidence-track"><span>对象</span><i /><span>关系</span><i /><span>时空</span><i /><span>结论</span></div><div className="eg-evidence-slots"><small>复核字段</small>{targets.map((target) => <button className={selected?.target_id === target.id ? 'is-match' : ''} data-edugame-correct={selected ? selected.correct !== false && selected.target_id === target.id : false} data-edugame-target={target.id} disabled={!active || !selected} key={target.id} onClick={() => onDrop(target.id)} type="button"><i /><span><strong>{target.label}</strong><small>接入证据链</small></span></button>)}</div></div>
    <style>{styles}</style>
  </section>;
}

function EvidenceChainCanvas() {
  const hostRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => { let app: any; let destroyed = false; import('pixi.js').then(async (PIXI) => { if (!hostRef.current || destroyed) return; app = new PIXI.Application(); await app.init({ width: 960, height: 540, background: '#071827', antialias: true, resolution: Math.min(window.devicePixelRatio || 1, 1.5) }); if (!hostRef.current || destroyed) { app.destroy(true); return; } hostRef.current.innerHTML = ''; hostRef.current.appendChild(app.canvas); const g = new PIXI.Graphics(); g.rect(0, 0, 960, 540).fill(0x071827); for (let y = 68; y < 520; y += 74) g.moveTo(0, y).lineTo(960, y).stroke({ width: 1, color: 0x20475b, alpha: .52 }); for (let x = 310; x < 710; x += 105) g.circle(x, 270, 24).fill(0x0b3348).stroke({ width: 2, color: 0x2dd4bf, alpha: .72 }); app.stage.addChild(g); const scan = new PIXI.Graphics().rect(0, 0, 4, 540).fill({ color: 0x22d3ee, alpha: .55 }); app.stage.addChild(scan); let x = 0; const animate = (ticker: any) => { x = (x + (ticker?.deltaTime ?? 1) * 2.2) % 960; scan.x = x; }; if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) app.ticker.add(animate); }).catch(() => { if (hostRef.current) hostRef.current.dataset.fallback = 'true'; }); return () => { destroyed = true; app?.destroy(true, { children: true }); }; }, []);
  return <div aria-hidden="true" className="eg-pixi-canvas eg-evidence-canvas" ref={hostRef} />;
}

const styles = `
.eg-evidence-chain{display:grid;gap:8px;color:#e8f7ff}.eg-evidence-chain>header{display:flex;align-items:end;justify-content:space-between}.eg-evidence-chain>header div{display:grid;gap:2px}.eg-evidence-chain>header span{color:#69c7c3;font-size:9px}.eg-evidence-chain>header strong{font-size:15px}.eg-evidence-chain>header em{color:#f2c55d;font-size:10px;font-style:normal}.eg-evidence-stage{position:relative;height:400px;display:grid;grid-template-columns:31% 1fr 31%;gap:15px;overflow:hidden;border:1px solid #244b60;border-radius:7px;padding:14px;background:#071827}.eg-evidence-canvas,.eg-evidence-canvas canvas{position:absolute!important;inset:0;width:100%!important;height:100%!important;object-fit:cover}.eg-evidence-inbox,.eg-evidence-slots{z-index:2;display:grid;grid-auto-rows:1fr;gap:6px;min-height:0}.eg-evidence-inbox>small,.eg-evidence-slots>small{color:#6f9aaa;font-size:8px}.eg-evidence-inbox button,.eg-evidence-slots button{min-height:0;display:grid;grid-template-columns:28px 1fr;align-items:center;gap:7px;border:1px solid #31566d;border-radius:5px;padding:6px 8px;color:#def4ff;background:#092337e8;text-align:left}.eg-evidence-inbox button>i,.eg-evidence-slots button>i{width:25px;height:25px;display:grid;place-items:center;border:1px solid #3da9b1;border-radius:4px;color:#5ff2da;font-size:9px;font-style:normal}.eg-evidence-inbox button span,.eg-evidence-slots button span{min-width:0;display:grid;gap:1px}.eg-evidence-inbox button strong,.eg-evidence-slots button strong{overflow:hidden;font-size:9px;text-overflow:ellipsis;white-space:nowrap}.eg-evidence-inbox button small,.eg-evidence-slots button small{color:#6c93a7;font-size:7px}.eg-evidence-inbox button.is-selected,.eg-evidence-slots button.is-match{border-color:#fde047;box-shadow:0 0 15px #fde0472e}.eg-evidence-inbox button.is-done{opacity:.32}.eg-evidence-track{z-index:2;display:grid;place-items:center;align-content:center;gap:8px}.eg-evidence-track span{width:72px;height:38px;display:grid;place-items:center;border:1px solid #31879a;border-radius:50%;color:#bff9f4;background:#0b3446;font-size:9px;font-weight:900;box-shadow:0 0 18px #22d3ee22}.eg-evidence-track i{width:2px;height:20px;background:#3bd3c8}.eg-evidence-chain.is-shake{animation:egEvidenceShake .24s linear}@keyframes egEvidenceShake{25%{transform:translateX(-4px)}75%{transform:translateX(4px)}}
`;
